# Generated by Django 2.2 on 2020-06-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Event Name')),
                ('description', models.TextField(max_length=400, verbose_name='Event Description')),
                ('created_on', models.DateField(auto_now=True)),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Event Time')),
                ('poster', models.ImageField(default='default_poster.png', upload_to='posters')),
                ('url', models.CharField(max_length=50)),
                ('registrations', models.IntegerField(default=0)),
                ('req_name', models.BooleanField(default=True, verbose_name='Name')),
                ('req_phone', models.BooleanField(default=True, verbose_name='Phone')),
                ('req_email', models.BooleanField(default=True, verbose_name='Email')),
                ('req_college', models.BooleanField(default=True, verbose_name='College')),
                ('req_image', models.BooleanField(default=False, verbose_name='Image')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Participant Name')),
                ('phone', models.CharField(default='', max_length=14, verbose_name='Participant Mobile')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Participant Email')),
                ('college', models.CharField(default='', max_length=100, verbose_name='Participant College')),
                ('image', models.ImageField(default='default_user.png', upload_to='participants')),
                ('date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
