# Generated by Django 2.2 on 2020-06-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hashed_url',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='college',
            field=models.CharField(default=' ', max_length=100, verbose_name='Participant College'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(default=' ', max_length=100, verbose_name='Participant Email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Participant Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=' ', max_length=14, verbose_name='Participant Mobile'),
        ),
    ]
