# Generated by Django 2.2 on 2020-06-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
